server:
  port: 9002
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ #多个eurekaserver之间用,隔开
  instance:
    prefer-ip-address: true #使用ip地址注册