spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: order
        uri: http://127.0.0.1:10001
        predicates:
        - Path=/order/**
      - id: product
        uri: http://127.0.0.1:10002
        predicates:
        - Path=/product/**